### PR TITLE
feature: add copy method

### PR DESCRIPTION
**Pull request by jeffrey82221**
Adding `copy` method to `DropboxDriveFileSystem`.

The method is tested upon the examples reference from fsspec copy interface definition: https://filesystem-spec.readthedocs.io/en/latest/copying.html. 

The test is written in pytest. Not sure how to convert it to Unittest. 

Please help me rewrite the pytest testing to Unittest testing.

### CODE REVIEW

**Comment by MarineChap** [comment]
Thanks!  Working on the text this week.

**Comment by MarineChap** [comment]
Actually I really don't have the time to switch it for unittest. I will keep it as pytest for now.

**Review by MarineChap — COMMENTED** [review]
In the fsspec, there is an option on_error: “raise”, “ignore”
See how it is used here: [AbstractFileSystem.copy](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/spec.html#AbstractFileSystem.copy)

Can you modify your assert to be raise only when the option on_error is raise and ignore in the other case please ? 
Thank you

**Comment by jeffrey82221** [comment]
Hi, sorry taking so long for replying.
I have added the `on_error` option on the assertion parts and the parts calling dbx.files_copy. Is the method now in the right behavior as you suggested?

I also change the dropbox token in test_copy to ‘123’, same as those in test.py. Could you help running the test to see if the method works successfully?

**Comment by MarineChap** [comment]
Great. I took a look at your test and actually what you are testing is if the copy with the dropbox API is working.
But here, I want to test only the dropboxdrivefs API. What i am doing is I mock call to the dropbox API while checking that I am calling these functions with the right parameters. 

This avoid having a dropbox instance running somewhere with the right API key.

**Pull request merged**
